"""add role_permissions table

Revision ID: 3d59e58bb439
Revises: 7725b9353605
Create Date: 2026-09-19 10:43:05.672002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d59e58bb439'
down_revision: Union[str, None] = '7725b9353605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
