"""drop physical foreign keys

Revision ID: 7725b9353605
Revises: 0dce3dffc60a
Create Date: 2026-09-18 22:36:21.837559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7725b9353605'
down_revision: Union[str, None] = '0dce3dffc60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_approvals_decided_by_fkey'), 'agent_approvals', type_='foreignkey')
    op.drop_constraint(op.f('agent_approvals_task_id_fkey'), 'agent_approvals', type_='foreignkey')
    op.drop_constraint(op.f('agent_tasks_user_id_fkey'), 'agent_tasks', type_='foreignkey')
    op.drop_constraint(op.f('agent_trace_events_task_id_fkey'), 'agent_trace_events', type_='foreignkey')
    op.drop_constraint(op.f('customer_tickets_customer_id_fkey'), 'customer_tickets', type_='foreignkey')
    op.drop_constraint(op.f('orders_product_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_customer_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('sales_records_product_id_fkey'), 'sales_records', type_='foreignkey')
    op.drop_constraint(op.f('sales_records_customer_id_fkey'), 'sales_records', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_role_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_user_id_fkey'), 'user_roles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('user_roles_user_id_fkey'), 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_roles_role_id_fkey'), 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('sales_records_customer_id_fkey'), 'sales_records', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('sales_records_product_id_fkey'), 'sales_records', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('orders_customer_id_fkey'), 'orders', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('orders_product_id_fkey'), 'orders', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('customer_tickets_customer_id_fkey'), 'customer_tickets', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('agent_trace_events_task_id_fkey'), 'agent_trace_events', 'agent_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('agent_tasks_user_id_fkey'), 'agent_tasks', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('agent_approvals_task_id_fkey'), 'agent_approvals', 'agent_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('agent_approvals_decided_by_fkey'), 'agent_approvals', 'users', ['decided_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
